### ISSUE TITLE
Use internal test report resources

### ISSUE THREAD

**Issue by Joonalai** [interactive-instruments/etf-webapp-docker#11]
When the test report finishes, the internal links css files are used:

http://localhost:8080/etf-webapp/css/de.interactive-instruments.min.css and 
http://localhost:8080/etf-webapp/css/de.interactive-instruments.rep.css

But when the page is refreshed or the test report is opened again, it tries to load the styles from:

http://resources.etf-validator.net/report/v2/css/de.interactive-instruments.min.css
http://resources.etf-validator.net/report/v2/css/de.interactive-instruments.rep.css

And also jQuery is loaded from http address instead of https address at that point:

http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.css
http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.11.3.min.js
http://ajax.googleapis.com/ajax/libs/jquerymobile/1.4.5/jquery.mobile.min.js

It would be good to use internal css files all along and jQuery with https address, like it is used elsewhere in the application.

**Comment by Joonalai** [comment]
By useing header *Content-Security-Policy: upgrade-insecure-requests* it is possible to get the jQuery resources, but since resources.etf-validator.net/ cannot be accessed with https, it does not solve whole problem.

**Comment by jonherrmann** [comment]
Thanks for reporting. Please report non-docker related issues in the etf-webapp repository next time.

I will close this issue here, you can keep track of it here: https://github.com/interactive-instruments/etf-webapp/issues/143

One "fix" for now: https access to the resources should be possible now.
