### ISSUE TITLE
Installation instructions are lacking

### ISSUE THREAD

**Issue by sampov2** [interactive-instruments/etf-webapp-docker#3]
The installation instructions tell that we should copy BaseX and SoapUI based tests to different directories within the docker container. However there is no clear instructions on where to get these tests, nor how to further organise these files under the docker container directories (i.e. should there be subdirectories etc.). I'm particularly interested in the INSPIRE validation tests.

**Comment by jonherrmann** [comment]
Thanks for the feedback. We will update the documentation.

The ets-repository structure changed. You need to download the test suites from here 
https://github.com/interactive-instruments/ets-repository/tree/master/inspire and copy the **inspire** directory  to the **/etf/projects/bsx** directory. 

The Inspire tests are only supported by the preview ALPHA 2 version of the validator, so you need to make sure to use the dev branch of this repository https://github.com/interactive-instruments/etf-webapp-docker/tree/dev .
