### ISSUE TITLE
Tests fail to run properly (INSPIRE tests)

### ISSUE THREAD

**Issue by sampov2** [interactive-instruments/etf-webapp-docker#6]
Running the validator from the dev branch works, but tests fail to complete. The results for all executable test results I've tried so far come up as 0 tests total ran (and zero for all result classes) and logs show that running the test failed.

For example, I tried running the "INSPIRE GML encoding" test using a small XML file. In this case I uploaded the file but the same things happen if I give the validator an URL instead. No optional parameters / credentials were set up.

Here is the log that was produced during running the validation: [etf-test-log.txt](https://github.com/interactive-instruments/etf-webapp-docker/files/734790/etf-test-log.txt)

Here is the complete log from the docker container: 
[etf-docker-log.txt](https://github.com/interactive-instruments/etf-webapp-docker/files/734792/etf-docker-log.txt) . I made sure that I did no other operations than run the test described above.

In connection with this issue, the application is unable to create reports for these failed tests. I'm mentioning this because it's difficult to say whether the reporting problems are due to the fact that the test failed or if this is indicative of an underlying issue causing the tests to fail. Here is a log file captured from docker logs when I choose "Download report" for the failed case above: [etf-test-report-log.txt](https://github.com/interactive-instruments/etf-webapp-docker/files/734805/etf-test-report-log.txt)

**Comment by jonherrmann** [comment]
Hi Sampo, thanks for the detailed issue report.

We have updated the test drivers to the latest version.
Please remove the contents of the directory /etf/td -if it exists. I' am not sure if it was mounted in your environment,but it is OK if it does not exist: then it is in your image and will be overwritten automatically.

Please also make sure that you [pull the latest image](https://github.com/interactive-instruments/etf-webapp-docker#update).

Let me know if this works

**Comment by sampov2** [comment]
Things definitely nudged forward and it seems a test was really started. However now the whole process seems to have gotten stuck the second the test started: The validation dialog never completed and the webapp was no longer responsive. Here are the logs from the server 
[etf-webapp-stuck.txt](https://github.com/interactive-instruments/etf-webapp-docker/files/744515/etf-webapp-stuck.txt). Please ask for more if you need more specific information.

I used the same test with the same GML file as before.

(PS. I removed the containers and the images and /etf in it's entirety to ensure everything was up-to-date)

**Comment by sampov2** [comment]
I'm still having this issue. Are there any news on this? 

Just in case it helps, I've attached a screenshot of what the validator looks after I open the validator after a full reset (=remove containers, images, /etf and start with docker-compose up): 
![etf-errors-startup](https://cloud.githubusercontent.com/assets/770750/23365662/81c348bc-fd0c-11e6-8547-b5e5da9c0bb2.png)

Those errors do disappear, but might be somehow related to this. There are no errors in the docker logs when that view is initialized.

**Comment by jonherrmann** [comment]
There are still open issues that block local installations.

There is a bug related to the ETS loading [#78](https://github.com/interactive-instruments/etf-webapp/issues/78) and the new issue you encounter is related to browser cached resources that are not reloaded [#76](https://github.com/interactive-instruments/etf-webapp/issues/76).

You could try to clear your browser cache. Issue 78 should not pop up as long as you do not update  the ETS while the instance is running.

We'll try to fix this in the next iteration.

**Comment by sampov2** [comment]
Thanks for the update. Is there any schedule for the next iteration, or is it released "when it's ready"?

**Comment by jonherrmann** [comment]
The version of that iteration will be available mid-March.

**Comment by jonherrmann** [comment]
Hi @sampov2 , we released the etf-2.0.0-beta version and added some more information for the docker installation [here](https://github.com/interactive-instruments/etf-webapp-docker#setup-etf-with-docker-compose). Please remove your existing /etf directory before you install this version.

**Comment by sampov2** [comment]
Hi @jonherrmann, the red warning boxed have disappeared, but still ran into some troubles. Here's what I did:
 * Removed /etf
 * Pulled the newest dev branch of etf-webapp-docker (I have no local changes)
 * Removed previous containers and docker images (both nginx as well as etf-webapp)
 * Ran docker-compose up -d

I then proceeded to run the "INSPIRE GML encoding" test for a small XML file.

The process got stuck in this screen: 
![image](https://cloud.githubusercontent.com/assets/770750/24353877/60a39a4a-12f8-11e7-9794-a266ebbfd836.png)

Here is the log from the etf-webapp container: [docker-logs-validation-crashed-20170327.txt](https://github.com/interactive-instruments/etf-webapp-docker/files/872284/docker-logs-validation-crashed-20170327.txt)

**Comment by jonherrmann** [comment]
Thanks for checking this again, @sampov2.

This is an internal problem in the Executable Test Suites. Can you either upload the test file or use the API to retrieve the test report as XML file: http://localhost:8080/v2/<ID in the Test Run log beginning with 8e41377d-...>.xml ?

**Comment by sampov2** [comment]
Here's the test file: 
[hydrography_lt_inspire_gml.zip](https://github.com/interactive-instruments/etf-webapp-docker/files/872430/hydrography_lt_inspire_gml.zip). I hope it helps solve the issue!

**Comment by sampov2** [comment]
Just a quick comment though: the test suite should never be interrupted by any level of issue in the executable test suite - a test process should complete normally no matter what.

**Comment by jonherrmann** [comment]
Thank you for the file.
> Just a quick comment though: the test suite should never be interrupted by any level of issue in the executable test suite - a test process should complete normally no matter what.

As far as i can see it from the log file the test run did not crash. Basically there are two issues here: the ETS references something that does not exist. You may retrieve the result data (see my comment above) but the returned xml will be (schema) invalid. Design decision here: don't give the user a report with unreliable or incomplete  information. To avoid these kind of issues in the ETS, I opened a task in the ets-repository#50 to automatically check these kind of references.

However, that no error message is shown, is the second issue we will address.

**Comment by sampov2** [comment]
Fair enough. As the process stalled from the user's point of view, my interpretaion/worry was that the validation process would have stalled for a programmatic integration into the validator as well.

**Comment by jonherrmann** [comment]
I am closing this since the issue should have been fixed. Feel free to open a new issue if you are experiencing problems with the current version.
