### ISSUE TITLE
Wrong exception message regarding the functx-1.0.xar installation

### ISSUE THREAD

**Issue by elisabettastruzzi** [interactive-instruments/etf-webapp-docker#8]
Following instructions in https://github.com/interactive-instruments/etf-webapp-docker, downloaded the ETF image in an Ubuntu 16 LTS virtual machine with docker 1.6 and behind the jrc proxy.
The etf-webapp is correctly reachable in localhost through the browser, now. 
Anyway we notice that there is a wrong information in the exception message regarding the bad installation of functx-1.0.xar:

`rg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataStorageService': Invocation of init method failed; nested exception is de.interactive_instruments.exceptions.InitializationException: FunctX XQuery Function Library installation failed. If a proxy server is used, set the Java Virtual Machine parameter 'http.proxyHost'. Otherwise download functx-1.0.xar manually, extract the file (it is a ZIP file) and copy it to the BaseXRepo folder 'repo' below folder /etf/ds/obj [bxerr:BXRE0001] Package 'http://files.basex.org/modules/expath/functx-1.0.xar' does not exist.
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)`

The  "BaseXRepo folder repo below folder /etf/ds/obj" suggestion is wrong, against the correct one  /etf/ds/db/repo/http-www.functx.com-1.0 as described in the http://docs.etf-validator.net/Admin_manuals/index.html#_etf_data_directory_structure documentation.

**Comment by jonherrmann** [comment]
Fixed, thanks for reporting this issue.

I guess, since you are testing the docker image now, you will stumble on this issue #1  next... If so, please just drop one line in issue #1.
